export default {
  APP_INITIALIZATION_ERROR: "APP_INITIALIZATION_ERROR",
  LOGIN_CUSTOMER_ERROR: "LOGIN_CUSTOMER_ERROR",
  SIGNUP_CUSTOMER_ERROR: "SIGNUP_CUSTOMER_ERROR",
  FETCHING_ALL_DEALS_ERROR: "FETCHING_ALL_DEALS_ERROR",
  FETCHING_SAVED_DEALS_ERROR: "FETCHING_SAVED_DEALS_ERROR",
  FETCHING_DEAL_DETAILS_ERROR: "FETCHING_DEAL_DETAILS_ERROR",
  FETCHING_VENDOR_DETAILS_ERROR: "FETCHING_VENDOR_DETAILS_ERROR",
  SAVING_DEAL_ERROR: "SAVING_DEAL_ERROR",
  UNSAVING_DEAL_ERROR: "UNSAVING_DEAL_ERROR",
  FETCHING_DEAL_CUSTOMER_DETAILS_ERROR: "FETCHING_DEAL_CUSTOMER_DETAILS_ERROR",
  FETCHING_LOYALTY_REWARD_DETAILS_ERROR:
    "FETCHING_LOYALTY_REWARD_DETAILS_ERROR",
  FETCHING_LOYALTY_REWARD_CUSTOMER_DETAILS_ERROR:
    "FETCHING_LOYALTY_REWARD_CUSTOMER_DETAILS_ERROR",
  FETCHING_ALL_LOYALTY_REWARDS_ERROR: "FETCHING_ALL_LOYALTY_REWARDS_ERROR",
  UNSUBSCRIBING_FROM_REWARD_CARD_PROGRAM_ERROR:
    "UNSUBSCRIBING_FROM_REWARD_CARD_PROGRAM_ERROR",
  SUBSCRIBING_TO_REWARD_CARD_PROGRAM_ERROR:
    "SUBSCRIBING_TO_REWARD_CARD_PROGRAM_ERROR",
  FETCHING_MY_LOYALTY_REWARDS_ERROR: "FETCHING_MY_LOYALTY_REWARDS_ERROR",
  CREATING_MY_DEAL_ERROR: "CREATING_MY_DEAL_ERROR",
  FETCHING_ALL_VENDORS_ERROR: "FETCHING_ALL_VENDORS_ERROR",
  FETCHING_FOLLOWED_VENDORS_ERROR: "FETCHING_FOLLOWED_VENDORS_ERROR",
  FETCHING_VENDOR_DEALS_ERROR: "FETCHING_VENDOR_DEALS_ERROR",
  UPDATING_CUSTOMER_ERROR: "UPDATING_CUSTOMER_ERROR",
  SENDING_PW_RECOVERY_EMAIL_ERROR: "SENDING_PW_RECOVERY_EMAIL_ERROR"
};
