export default {
  INITIALIZING_APP: "INITIALIZING_APP",
  LOGGING_IN_CUSTOMER: "LOGGING_IN_CUSTOMER",
  SIGNING_UP_CUSTOMER: "SIGNING_UP_CUSTOMER",
  FETCHING_ALL_DEALS: "FETCHING_ALL_DEALS",
  FETCHING_SAVED_DEALS: "FETCHING_SAVED_DEALS",
  FETCHING_DEAL_DETAILS: "FETCHING_DEAL_DETAILS",
  FETCHING_VENDOR_DETAILS: "FETCHING_VENDOR_DETAILS",
  SAVING_DEAL: "SAVING_DEAL",
  UNSAVING_DEAL: "UNSAVING_DEAL",
  FETCHING_DEAL_CUSTOMER_DETAILS: "FETCHING_DEAL_CUSTOMER_DETAILS",
  FETCHING_LOYALTY_REWARD_DETAILS: "FETCHING_LOYALTY_REWARD_DETAILS",
  FETCHING_LOYALTY_REWARD_CUSTOMER_DETAILS:
    "FETCHING_LOYALTY_REWARD_CUSTOMER_DETAILS",
  FETCHING_ALL_LOYALTY_REWARDS: "FETCHING_ALL_LOYALTY_REWARDS",
  UNSUBSCRIBING_FROM_REWARD_CARD_PROGRAM:
    "UNSUBSCRIBING_FROM_REWARD_CARD_PROGRAM",
  SUBSCRIBING_TO_REWARD_CARD_PROGRAM: "SUBSCRIBING_TO_REWARD_CARD_PROGRAM",
  FETCHING_MY_LOYALTY_REWARDS: "FETCHING_MY_LOYALTY_REWARDS",
  CREATING_MY_DEAL: "CREATING_MY_DEAL",
  FETCHING_ALL_VENDORS: "FETCHING_ALL_VENDORS",
  FETCHING_FOLLOWED_VENDORS: "FETCHING_FOLLOWED_VENDORS",
  FETCHING_VENDOR_DEALS: "FETCHING_VENDOR_DEALS",
  UPDATING_CUSTOMER: "UPDATING_CUSTOMER",
  SENDING_PW_RECOVERY_EMAIL: "SENDING_PW_RECOVERY_EMAIL",
  FETCHING_VENDOR_REWARDS: "FETCHING_VENDOR_REWARDS",
  FETCHING_VENDOR_REVIEWS: "FETCHING_VENDOR_REVIEWS",
  SEARCHING_DEALS: "SEARCHING_DEALS",
  SEARCHING_VENDORS: "SEARCHING_VENDORS",
  LOGGING_OUT_CUSTOMER: "LOGGING_OUT_CUSTOMER",
  FETCHING_VENDOR_REVIEW_METRICS: "FETCHING_VENDOR_REVIEW_METRICS",
  FETCHING_CUSTOMER_VENDOR_REVIEW_METRICS:
    "FETCHING_CUSTOMER_VENDOR_REVIEW_METRICS"
};
