export default {
  FETCHED_ALL_REWARDS: "FETCHED_ALL_REWARDS",
  UNSUBSCRIBED_FROM_REWARD_CARD_PROGRAM:
    "UNSUBSCRIBED_FROM_REWARD_CARD_PROGRAM",
  SUBSCRIBED_TO_REWARD_CARD_PROGRAM: "SUBSCRIBED_TO_REWARD_CARD_PROGRAM"
};
